import os
import uuid
from google.cloud import aiplatform
# Importing the specific model class might change based on SDK versions,
# Using the .from_pretrained method is generally more stable.
# from google.cloud.aiplatform.gapic import ImageGenerationModel # Not strictly needed if using .from_pretrained

# Environment variables for Vertex AI configuration
VERTEX_AI_PROJECT_ID = os.getenv("VERTEX_AI_PROJECT_ID")
VERTEX_AI_LOCATION = os.getenv("VERTEX_AI_LOCATION") # e.g., "us-central1"
# Define the static folder path relative to this client file's location
# Assuming this client is in generative_ai_app directory.
STATIC_FOLDER_PATH = os.path.join(os.path.dirname(__file__), 'static')


is_image_client_configured = False
imagen_model = None # Global variable for the model client

# Ensure the static directory exists when the module is loaded
if not os.path.exists(STATIC_FOLDER_PATH):
    try:
        os.makedirs(STATIC_FOLDER_PATH)
        print(f"Created static directory at: {STATIC_FOLDER_PATH}")
    except OSError as e:
        print(f"Error creating static directory {STATIC_FOLDER_PATH}: {e}. Images may not save.")


def ensure_configured(model_name: str = "imagegeneration@006"): # Using a more recent stable version
    """
    Ensures the Vertex AI client is configured for Imagen.
    Initializes aiplatform and loads the Imagen model.
    """
    global is_image_client_configured, imagen_model

    if is_image_client_configured and imagen_model:
        # Could add a check here if model_name differs, then re-init model
        return True

    if not VERTEX_AI_PROJECT_ID:
        print("CRITICAL: VERTEX_AI_PROJECT_ID environment variable not set.")
        return False
    if not VERTEX_AI_LOCATION:
        print("CRITICAL: VERTEX_AI_LOCATION environment variable not set.")
        return False

    try:
        print(f"Configuring Vertex AI client for project '{VERTEX_AI_PROJECT_ID}' in location '{VERTEX_AI_LOCATION}'...")
        aiplatform.init(project=VERTEX_AI_PROJECT_ID, location=VERTEX_AI_LOCATION)

        print(f"Loading Imagen model '{model_name}'...")
        # Load the model
        imagen_model = aiplatform.ImageGenerationModel.from_pretrained(model_name)
        print("Vertex AI Imagen model loaded successfully.")
        is_image_client_configured = True
        return True
    except Exception as e:
        print(f"Error configuring Vertex AI client or loading Imagen model: {e}")
        is_image_client_configured = False
        imagen_model = None
        return False

def generate_image_from_prompt(prompt: str, output_file_basename: str = "generated_image") -> dict:
    """
    Generates an image based on a prompt using Vertex AI Imagen and saves it.

    Args:
        prompt: The text prompt to generate an image from.
        output_file_basename: The base name for the output file (without extension).
                              A UUID will be appended to ensure uniqueness.

    Returns:
        A dictionary containing either an 'image_url' (local path) or an 'error'.
    """
    global imagen_model
    if not ensure_configured(): # Default model "imagegeneration@006" will be used
        return {'error': "Vertex AI Image client not configured. Check project/location environment variables."}

    if not imagen_model:
        return {'error': "Imagen model is not available even after configuration attempt."}

    print(f"Generating image with Vertex AI Imagen for prompt: '{prompt}'")

    try:
        # Generate images. The API can return multiple, we'll take the first.
        # Parameters like number_of_images, aspect_ratio, etc., can be added here.
        response = imagen_model.generate_images(
            prompt=prompt,
            number_of_images=1, # Generate one image
            # seed=xxxx # Optional: for reproducibility
            # aspect_ratio="1:1" # Optional: e.g., "1:1", "16:9", "9:16"
        )

        if not response.images:
            print("Error: Vertex AI Imagen did not return any images.")
            return {'error': "No images generated by the model."}

        image_bytes = response.images[0]._image_bytes # Accessing the private attribute for bytes

        # Create a unique filename to avoid overwrites
        unique_id = uuid.uuid4()
        output_filename_png = f"{output_file_basename}_{unique_id}.png"
        image_path = os.path.join(STATIC_FOLDER_PATH, output_filename_png)

        with open(image_path, 'wb') as f:
            f.write(image_bytes)

        print(f"Image saved to: {image_path}")

        # Return a URL path that Flask can serve
        image_url = f"/static/{output_filename_png}"
        return {'image_url': image_url}

    except Exception as e:
        # This could be due to various reasons: quota, invalid prompt, API errors, etc.
        print(f"Error generating image with Vertex AI Imagen: {e}")
        # More specific error parsing could be done here if the SDK provides structured errors
        error_message = str(e)
        if "quota" in error_message.lower():
            return {'error': "Image generation failed due to quota issues. Please check your Vertex AI quota."}
        elif "invalid prompt" in error_message.lower() or "rejected" in error_message.lower(): # Heuristic
            return {'error': "Image generation failed: The prompt was considered invalid or rejected by the safety filters."}
        return {'error': f"Image generation failed: {error_message}"}

if __name__ == '__main__':
    print("Testing image_client.py with actual Vertex AI Imagen calls...")

    # IMPORTANT: For this test to run, you MUST have:
    # 1. google-cloud-aiplatform installed.
    # 2. Environment variables VERTEX_AI_PROJECT_ID and VERTEX_AI_LOCATION set.
    # 3. Your Google Cloud account authenticated (e.g., via `gcloud auth application-default login`).
    # 4. The Vertex AI API enabled in your Google Cloud project.
    # 5. Sufficient quota for Imagen.

    if not VERTEX_AI_PROJECT_ID or not VERTEX_AI_LOCATION:
        print("\nWARNING: VERTEX_AI_PROJECT_ID and/or VERTEX_AI_LOCATION are not set.")
        print("Actual API calls will not be made. Set these to test full functionality.")
        # Example of how ensure_configured would be called:
        if ensure_configured():
            print("Test configuration call successful (or would be if env vars were set).")
        else:
            print("Test configuration call failed. See errors above if any, or check env vars.")
    else:
        print(f"Using Project ID: {VERTEX_AI_PROJECT_ID}, Location: {VERTEX_AI_LOCATION}")
        if ensure_configured(): # This will attempt to load the model
            test_prompt_cat = "A photo of a fluffy ginger cat wearing a tiny blue party hat, sitting on a wooden table, realistic."
            print(f"\nTest 1: Generating image for prompt: '{test_prompt_cat}'")
            result_cat = generate_image_from_prompt(test_prompt_cat)
            if 'image_url' in result_cat:
                print(f"Generated image URL: {result_cat['image_url']}")
            elif 'error' in result_cat:
                print(f"Error for cat prompt: {result_cat['error']}")

            test_prompt_landscape = "A serene landscape with mountains and a lake at sunset, digital art."
            print(f"\nTest 2: Generating image for prompt: '{test_prompt_landscape}'")
            result_landscape = generate_image_from_prompt(test_prompt_landscape)
            if 'image_url' in result_landscape:
                print(f"Generated image URL: {result_landscape['image_url']}")
            elif 'error' in result_landscape:
                print(f"Error for landscape prompt: {result_landscape['error']}")
        else:
            print("Could not configure the Vertex AI client for testing. Check logs and environment variables.")
